package com.hope_studio.video_maker_slideshow_maker.ho_data

import com.hope_studio.video_maker_slideshow_maker.ho_gs_effect.GSEffectUtils

class GSEffectData(val effectType: GSEffectUtils.EffectType)