package com.hope_studio.video_maker_slideshow_maker.slide_show_transition.transition

import com.hope_studio.video_maker_slideshow_maker.R

open class GSButterflyWaveTransition :GSTransition(R.raw.butterfly_wave_scrawler_transition_code, "ButterflyWave")