package com.acatapps.videomaker;

import java.util.ArrayList;
import java.util.List;

public class StickerFileAsset {

    public static ArrayList<String> amojiList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/amoji/01.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/02.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/03.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/04.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/05.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/06.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/07.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/08.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/09.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/10.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/11.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/12.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/13.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/14.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/15.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/16.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/17.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/18.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/19.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/20.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/21.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/22.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/23.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/24.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/25.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/26.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/27.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/28.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/29.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/30.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/31.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/32.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/33.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/34.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/35.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/36.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/37.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/38.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/39.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/40.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/41.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/42.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/43.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/44.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/45.webp");
        arrayList.add("base_ads/uploads/stickers/amoji/46.webp");
        return arrayList;
    }

    public static ArrayList<String> bubbleList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/bubble/01.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/02.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/03.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/04.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/05.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/06.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/07.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/08.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/09.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/10.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/11.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/12.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/13.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/14.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/15.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/16.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/17.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/18.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/19.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/20.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/21.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/22.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/23.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/24.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/25.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/26.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/27.webp");
        arrayList.add("base_ads/uploads/stickers/bubble/28.webp");
        return arrayList;
    }

    public static ArrayList<String> rageList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/rage/01.webp");
        arrayList.add("base_ads/uploads/stickers/rage/02.webp");
        arrayList.add("base_ads/uploads/stickers/rage/03.webp");
        arrayList.add("base_ads/uploads/stickers/rage/04.webp");
        arrayList.add("base_ads/uploads/stickers/rage/05.webp");
        arrayList.add("base_ads/uploads/stickers/rage/06.webp");
        arrayList.add("base_ads/uploads/stickers/rage/07.webp");
        arrayList.add("base_ads/uploads/stickers/rage/08.webp");
        arrayList.add("base_ads/uploads/stickers/rage/09.webp");
        arrayList.add("base_ads/uploads/stickers/rage/10.webp");
        arrayList.add("base_ads/uploads/stickers/rage/11.webp");
        arrayList.add("base_ads/uploads/stickers/rage/12.webp");
        arrayList.add("base_ads/uploads/stickers/rage/13.webp");
        arrayList.add("base_ads/uploads/stickers/rage/14.webp");
        arrayList.add("base_ads/uploads/stickers/rage/15.webp");
        arrayList.add("base_ads/uploads/stickers/rage/16.webp");
        arrayList.add("base_ads/uploads/stickers/rage/17.webp");
        arrayList.add("base_ads/uploads/stickers/rage/18.webp");
        arrayList.add("base_ads/uploads/stickers/rage/19.webp");
        arrayList.add("base_ads/uploads/stickers/rage/20.webp");
        arrayList.add("base_ads/uploads/stickers/rage/21.webp");
        arrayList.add("base_ads/uploads/stickers/rage/22.webp");
        arrayList.add("base_ads/uploads/stickers/rage/23.webp");
        arrayList.add("base_ads/uploads/stickers/rage/24.webp");
        arrayList.add("base_ads/uploads/stickers/rage/25.webp");
        arrayList.add("base_ads/uploads/stickers/rage/26.webp");
        arrayList.add("base_ads/uploads/stickers/rage/27.webp");
        arrayList.add("base_ads/uploads/stickers/rage/28.webp");
        arrayList.add("base_ads/uploads/stickers/rage/29.webp");
        arrayList.add("base_ads/uploads/stickers/rage/30.webp");
        arrayList.add("base_ads/uploads/stickers/rage/31.webp");
        arrayList.add("base_ads/uploads/stickers/rage/32.webp");
        arrayList.add("base_ads/uploads/stickers/rage/33.webp");
        arrayList.add("base_ads/uploads/stickers/rage/34.webp");
        arrayList.add("base_ads/uploads/stickers/rage/35.webp");
        arrayList.add("base_ads/uploads/stickers/rage/36.webp");
        arrayList.add("base_ads/uploads/stickers/rage/37.webp");
        arrayList.add("base_ads/uploads/stickers/rage/38.webp");
        arrayList.add("base_ads/uploads/stickers/rage/39.webp");
        arrayList.add("base_ads/uploads/stickers/rage/40.webp");
        arrayList.add("base_ads/uploads/stickers/rage/41.webp");
        arrayList.add("base_ads/uploads/stickers/rage/42.webp");
        arrayList.add("base_ads/uploads/stickers/rage/43.webp");
        arrayList.add("base_ads/uploads/stickers/rage/44.webp");
        arrayList.add("base_ads/uploads/stickers/rage/45.webp");
        arrayList.add("base_ads/uploads/stickers/rage/46.webp");
        arrayList.add("base_ads/uploads/stickers/rage/47.webp");
        arrayList.add("base_ads/uploads/stickers/rage/48.webp");
        arrayList.add("base_ads/uploads/stickers/rage/49.webp");
        arrayList.add("base_ads/uploads/stickers/rage/50.webp");
        arrayList.add("base_ads/uploads/stickers/rage/51.webp");
        arrayList.add("base_ads/uploads/stickers/rage/52.webp");
        arrayList.add("base_ads/uploads/stickers/rage/53.webp");
        arrayList.add("base_ads/uploads/stickers/rage/54.webp");
        arrayList.add("base_ads/uploads/stickers/rage/55.webp");
        arrayList.add("base_ads/uploads/stickers/rage/56.webp");
        arrayList.add("base_ads/uploads/stickers/rage/57.webp");
        arrayList.add("base_ads/uploads/stickers/rage/58.webp");
        arrayList.add("base_ads/uploads/stickers/rage/59.webp");
        arrayList.add("base_ads/uploads/stickers/rage/60.webp");
        arrayList.add("base_ads/uploads/stickers/rage/61.webp");
        arrayList.add("base_ads/uploads/stickers/rage/62.webp");
        arrayList.add("base_ads/uploads/stickers/rage/63.webp");
        arrayList.add("base_ads/uploads/stickers/rage/64.webp");
        arrayList.add("base_ads/uploads/stickers/rage/65.webp");
        arrayList.add("base_ads/uploads/stickers/rage/66.webp");
        arrayList.add("base_ads/uploads/stickers/rage/67.webp");
        arrayList.add("base_ads/uploads/stickers/rage/68.webp");
        arrayList.add("base_ads/uploads/stickers/rage/69.webp");
        arrayList.add("base_ads/uploads/stickers/rage/70.webp");
        arrayList.add("base_ads/uploads/stickers/rage/71.webp");
        arrayList.add("base_ads/uploads/stickers/rage/72.webp");
        arrayList.add("base_ads/uploads/stickers/rage/73.webp");
        arrayList.add("base_ads/uploads/stickers/rage/74.webp");
        arrayList.add("base_ads/uploads/stickers/rage/75.webp");
        arrayList.add("base_ads/uploads/stickers/rage/76.webp");
        arrayList.add("base_ads/uploads/stickers/rage/77.webp");
        arrayList.add("base_ads/uploads/stickers/rage/78.webp");
        arrayList.add("base_ads/uploads/stickers/rage/79.webp");
        arrayList.add("base_ads/uploads/stickers/rage/80.webp");
        arrayList.add("base_ads/uploads/stickers/rage/81.webp");
        arrayList.add("base_ads/uploads/stickers/rage/82.webp");
        arrayList.add("base_ads/uploads/stickers/rage/83.webp");
        arrayList.add("base_ads/uploads/stickers/rage/84.webp");
        arrayList.add("base_ads/uploads/stickers/rage/85.webp");
        arrayList.add("base_ads/uploads/stickers/rage/86.webp");
        arrayList.add("base_ads/uploads/stickers/rage/87.webp");
        arrayList.add("base_ads/uploads/stickers/rage/88.webp");
        arrayList.add("base_ads/uploads/stickers/rage/89.webp");
        arrayList.add("base_ads/uploads/stickers/rage/90.webp");
        arrayList.add("base_ads/uploads/stickers/rage/91.webp");
        arrayList.add("base_ads/uploads/stickers/rage/92.webp");
        arrayList.add("base_ads/uploads/stickers/rage/93.webp");
        arrayList.add("base_ads/uploads/stickers/rage/94.webp");
        arrayList.add("base_ads/uploads/stickers/rage/95.webp");
        arrayList.add("base_ads/uploads/stickers/rage/96.webp");
        arrayList.add("base_ads/uploads/stickers/rage/97.webp");
        arrayList.add("base_ads/uploads/stickers/rage/98.webp");
        arrayList.add("base_ads/uploads/stickers/rage/99.webp");
        return arrayList;
    }

    public static ArrayList<String> cartoonList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/cartoon/01.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/02.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/03.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/04.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/05.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/06.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/07.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/08.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/09.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/10.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/11.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/12.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/13.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/14.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/15.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/16.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/17.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/18.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/19.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/20.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/21.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/22.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/23.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/24.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/25.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/26.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/27.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/28.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/29.webp");
        arrayList.add("base_ads/uploads/stickers/cartoon/30.webp");
        return arrayList;
    }

    public static ArrayList<String> christmasList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/christmas/01.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/02.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/03.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/04.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/05.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/06.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/07.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/08.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/09.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/10.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/11.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/12.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/13.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/14.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/15.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/16.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/17.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/18.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/19.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/20.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/21.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/22.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/23.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/24.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/25.webp");
        arrayList.add("base_ads/uploads/stickers/christmas/26.webp");
        return arrayList;
    }

    public static ArrayList<String> childList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/child/01.webp");
        arrayList.add("base_ads/uploads/stickers/child/02.webp");
        arrayList.add("base_ads/uploads/stickers/child/03.webp");
        arrayList.add("base_ads/uploads/stickers/child/04.webp");
        arrayList.add("base_ads/uploads/stickers/child/05.webp");
        arrayList.add("base_ads/uploads/stickers/child/06.webp");
        arrayList.add("base_ads/uploads/stickers/child/07.webp");
        arrayList.add("base_ads/uploads/stickers/child/08.webp");
        arrayList.add("base_ads/uploads/stickers/child/09.webp");
        arrayList.add("base_ads/uploads/stickers/child/10.webp");
        arrayList.add("base_ads/uploads/stickers/child/11.webp");
        arrayList.add("base_ads/uploads/stickers/child/12.webp");
        arrayList.add("base_ads/uploads/stickers/child/13.webp");
        arrayList.add("base_ads/uploads/stickers/child/14.webp");
        arrayList.add("base_ads/uploads/stickers/child/15.webp");
        arrayList.add("base_ads/uploads/stickers/child/16.webp");
        arrayList.add("base_ads/uploads/stickers/child/17.webp");
        arrayList.add("base_ads/uploads/stickers/child/18.webp");
        arrayList.add("base_ads/uploads/stickers/child/19.webp");
        arrayList.add("base_ads/uploads/stickers/child/20.webp");
        arrayList.add("base_ads/uploads/stickers/child/21.webp");
        arrayList.add("base_ads/uploads/stickers/child/22.webp");
        arrayList.add("base_ads/uploads/stickers/child/23.webp");
        arrayList.add("base_ads/uploads/stickers/child/24.webp");
        arrayList.add("base_ads/uploads/stickers/child/25.webp");
        arrayList.add("base_ads/uploads/stickers/child/26.webp");
        arrayList.add("base_ads/uploads/stickers/child/27.webp");
        arrayList.add("base_ads/uploads/stickers/child/28.webp");
        return arrayList;
    }

    public static ArrayList<String> deliciousList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/delicious/01.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/02.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/03.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/04.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/05.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/06.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/07.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/08.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/09.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/10.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/11.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/12.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/13.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/14.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/15.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/16.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/17.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/18.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/19.webp");
        arrayList.add("base_ads/uploads/stickers/delicious/20.webp");
        return arrayList;
    }

    public static ArrayList<String> emojList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/emoj/01.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/02.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/03.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/04.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/05.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/06.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/07.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/08.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/09.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/10.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/11.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/12.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/13.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/14.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/15.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/16.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/17.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/18.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/19.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/20.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/21.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/22.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/23.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/24.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/25.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/26.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/27.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/28.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/29.webp");
        arrayList.add("base_ads/uploads/stickers/emoj/30.webp");
        return arrayList;
    }

    public static ArrayList<String> flowerList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/flower/01.webp");
        arrayList.add("base_ads/uploads/stickers/flower/02.webp");
        arrayList.add("base_ads/uploads/stickers/flower/03.webp");
        arrayList.add("base_ads/uploads/stickers/flower/04.webp");
        arrayList.add("base_ads/uploads/stickers/flower/05.webp");
        arrayList.add("base_ads/uploads/stickers/flower/06.webp");
        arrayList.add("base_ads/uploads/stickers/flower/07.webp");
        arrayList.add("base_ads/uploads/stickers/flower/08.webp");
        arrayList.add("base_ads/uploads/stickers/flower/09.webp");
        arrayList.add("base_ads/uploads/stickers/flower/10.webp");
        arrayList.add("base_ads/uploads/stickers/flower/11.webp");
        arrayList.add("base_ads/uploads/stickers/flower/12.webp");
        arrayList.add("base_ads/uploads/stickers/flower/13.webp");
        arrayList.add("base_ads/uploads/stickers/flower/14.webp");
        arrayList.add("base_ads/uploads/stickers/flower/15.webp");
        arrayList.add("base_ads/uploads/stickers/flower/16.webp");
        arrayList.add("base_ads/uploads/stickers/flower/17.webp");
        arrayList.add("base_ads/uploads/stickers/flower/18.webp");
        arrayList.add("base_ads/uploads/stickers/flower/19.webp");
        arrayList.add("base_ads/uploads/stickers/flower/20.webp");
        arrayList.add("base_ads/uploads/stickers/flower/21.webp");
        arrayList.add("base_ads/uploads/stickers/flower/22.webp");
        arrayList.add("base_ads/uploads/stickers/flower/23.webp");
        arrayList.add("base_ads/uploads/stickers/flower/24.webp");
        arrayList.add("base_ads/uploads/stickers/flower/25.webp");
        arrayList.add("base_ads/uploads/stickers/flower/26.webp");
        arrayList.add("base_ads/uploads/stickers/flower/27.webp");
        arrayList.add("base_ads/uploads/stickers/flower/28.webp");
        arrayList.add("base_ads/uploads/stickers/flower/29.webp");
        arrayList.add("base_ads/uploads/stickers/flower/30.webp");
        arrayList.add("base_ads/uploads/stickers/flower/31.webp");
        arrayList.add("base_ads/uploads/stickers/flower/32.webp");
        arrayList.add("base_ads/uploads/stickers/flower/33.webp");
        arrayList.add("base_ads/uploads/stickers/flower/34.webp");
        arrayList.add("base_ads/uploads/stickers/flower/35.webp");
        arrayList.add("base_ads/uploads/stickers/flower/36.webp");
        arrayList.add("base_ads/uploads/stickers/flower/37.webp");
        arrayList.add("base_ads/uploads/stickers/flower/38.webp");
        arrayList.add("base_ads/uploads/stickers/flower/39.webp");
        arrayList.add("base_ads/uploads/stickers/flower/40.webp");
        arrayList.add("base_ads/uploads/stickers/flower/41.webp");
        arrayList.add("base_ads/uploads/stickers/flower/42.webp");
        arrayList.add("base_ads/uploads/stickers/flower/43.webp");
        arrayList.add("base_ads/uploads/stickers/flower/44.webp");
        arrayList.add("base_ads/uploads/stickers/flower/45.webp");
        arrayList.add("base_ads/uploads/stickers/flower/46.webp");
        return arrayList;
    }

    public static ArrayList<String> handList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/hand/01.webp");
        arrayList.add("base_ads/uploads/stickers/hand/02.webp");
        arrayList.add("base_ads/uploads/stickers/hand/03.webp");
        arrayList.add("base_ads/uploads/stickers/hand/04.webp");
        arrayList.add("base_ads/uploads/stickers/hand/05.webp");
        arrayList.add("base_ads/uploads/stickers/hand/06.webp");
        arrayList.add("base_ads/uploads/stickers/hand/07.webp");
        arrayList.add("base_ads/uploads/stickers/hand/08.webp");
        arrayList.add("base_ads/uploads/stickers/hand/09.webp");
        arrayList.add("base_ads/uploads/stickers/hand/10.webp");
        arrayList.add("base_ads/uploads/stickers/hand/11.webp");
        arrayList.add("base_ads/uploads/stickers/hand/12.webp");
        arrayList.add("base_ads/uploads/stickers/hand/13.webp");
        arrayList.add("base_ads/uploads/stickers/hand/14.webp");
        arrayList.add("base_ads/uploads/stickers/hand/15.webp");
        arrayList.add("base_ads/uploads/stickers/hand/16.webp");
        arrayList.add("base_ads/uploads/stickers/hand/17.webp");
        arrayList.add("base_ads/uploads/stickers/hand/18.webp");
        arrayList.add("base_ads/uploads/stickers/hand/19.webp");
        arrayList.add("base_ads/uploads/stickers/hand/20.webp");
        arrayList.add("base_ads/uploads/stickers/hand/21.webp");
        arrayList.add("base_ads/uploads/stickers/hand/22.webp");
        arrayList.add("base_ads/uploads/stickers/hand/23.webp");
        arrayList.add("base_ads/uploads/stickers/hand/24.webp");
        arrayList.add("base_ads/uploads/stickers/hand/25.webp");
        return arrayList;
    }

    public static ArrayList<String> popularList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/popular/01.webp");
        arrayList.add("base_ads/uploads/stickers/popular/02.webp");
        arrayList.add("base_ads/uploads/stickers/popular/03.webp");
        arrayList.add("base_ads/uploads/stickers/popular/04.webp");
        arrayList.add("base_ads/uploads/stickers/popular/05.webp");
        arrayList.add("base_ads/uploads/stickers/popular/06.webp");
        arrayList.add("base_ads/uploads/stickers/popular/07.webp");
        arrayList.add("base_ads/uploads/stickers/popular/08.webp");
        arrayList.add("base_ads/uploads/stickers/popular/09.webp");
        arrayList.add("base_ads/uploads/stickers/popular/10.webp");
        arrayList.add("base_ads/uploads/stickers/popular/11.webp");
        arrayList.add("base_ads/uploads/stickers/popular/12.webp");
        arrayList.add("base_ads/uploads/stickers/popular/13.webp");
        arrayList.add("base_ads/uploads/stickers/popular/14.webp");
        arrayList.add("base_ads/uploads/stickers/popular/15.webp");
        arrayList.add("base_ads/uploads/stickers/popular/16.webp");
        arrayList.add("base_ads/uploads/stickers/popular/17.webp");
        arrayList.add("base_ads/uploads/stickers/popular/18.webp");
        return arrayList;
    }

    public static ArrayList<String> rainbowList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/rainbow/01.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/02.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/03.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/04.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/05.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/06.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/07.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/08.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/09.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/10.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/11.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/12.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/13.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/14.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/15.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/16.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/17.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/18.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/19.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/20.webp");
        arrayList.add("base_ads/uploads/stickers/rainbow/21.webp");
        return arrayList;
    }

    public static ArrayList<String> stickerList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/sticker/01.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/02.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/03.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/04.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/05.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/06.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/07.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/08.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/09.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/10.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/11.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/12.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/13.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/14.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/15.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/16.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/17.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/18.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/19.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/20.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/21.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/22.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/23.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/24.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/25.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/26.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/27.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/28.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/29.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/30.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/31.webp");
        arrayList.add("base_ads/uploads/stickers/sticker/32.webp");
        return arrayList;
    }

    public static ArrayList<String> unicornList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/unicorn/01.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/02.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/03.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/04.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/05.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/06.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/07.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/08.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/09.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/10.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/11.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/12.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/13.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/14.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/15.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/16.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/17.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/18.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/19.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/20.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/21.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/22.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/23.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/24.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/25.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/26.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/27.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/28.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/29.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/30.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/31.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/32.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/33.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/34.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/35.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/36.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/37.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/38.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/39.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/40.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/41.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/42.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/43.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/44.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/45.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/46.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/47.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/48.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/49.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/50.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/51.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/52.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/53.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/54.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/55.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/56.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/57.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/58.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/59.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/60.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/61.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/62.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/63.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/64.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/65.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/66.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/67.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/68.webp");
        arrayList.add("base_ads/uploads/stickers/unicorn/69.webp");
        return arrayList;
    }

    public static ArrayList<String> valentineList() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("base_ads/uploads/stickers/valentine/01.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/02.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/03.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/04.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/05.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/06.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/07.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/08.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/09.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/10.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/11.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/12.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/13.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/14.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/15.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/16.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/17.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/18.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/19.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/20.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/21.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/22.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/23.webp");
        arrayList.add("base_ads/uploads/stickers/valentine/24.webp");
        return arrayList;
    }
}